name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]
  
jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install and lint backend
      run: |
        cd backend
        npm install
        npm run lint

    - name: Test backend
      run: |
        cd backend
        npm run test

    - name: Audit backend dependencies
      run: |
        cd backend
        npm audit --audit-level=moderate || true

    - name: Install and lint frontend
      run: |
        cd frontend
        npm install
        npm run lint || true

    - name: Test frontend
      run: |
        cd frontend
        npm run test -- --watchAll=false
        
    - name: Debug
      run: |
        echo "PATH: $PATH"
        which docker
        docker --version

    - name: Debug React install
      run: |
        cd frontend
        npm install
        ls node_modules/react-scripts || echo "react-scripts not found"
    
    - name: Trivy Scan (Backend)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecops-backend'
   
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: |
        docker build -t devsecops-frontend ./frontend
        docker build -t devsecops-backend ./backend

    - name: Trivy Scan (Backend)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecops-backend'

    - name: Trivy Scan (Frontend)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'devsecops-frontend'
